import { ArrowDownRight, ArrowUpRight, BarChart3, BookOpen, Camera, ChevronRight, CircleAlert, Leaf, Radio, ScanLine, Sprout } from "lucide-react";
import { Link } from "react-router-dom";
import { coreFeatures, heroAlt, heroImagePath, homepageHeroCopy, homepageHeroMicrocopy, homepageHeroTitle, symptomSigns } from "@/data/diseases";

export default function Home() {
  return <div>
    <section className="relative overflow-hidden border-b border-[#2D5016]/10 bg-[#F5F3ED]">
      <div className="container grid min-h-[690px] items-center gap-12 py-16 lg:grid-cols-[.92fr_1.08fr] lg:py-24">
        <div className="relative z-10 max-w-2xl">
          <p className="eyebrow mb-7 flex items-center gap-3"><span className="inline-block h-px w-9 bg-[#B85C4D]" />Field-first crop health</p>
          <h1 className="display-xl max-w-4xl text-[#2D5016]">{homepageHeroTitle}</h1>
          <p className="mt-8 max-w-lg text-lg leading-relaxed text-[#5F665B]">{homepageHeroCopy}</p>
          <div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link to="/scanner" className="button-primary px-6 py-4">Start a demo screen <ArrowUpRight size={16} /></Link><Link to="/library" className="button-secondary px-6 py-4">Browse disease library</Link></div>
          <p className="mt-7 max-w-md font-mono text-[.68rem] uppercase leading-relaxed tracking-[.12em] text-[#7C8479]">{homepageHeroMicrocopy}</p>
        </div>
        <div className="relative mx-auto w-full max-w-[650px] lg:ml-auto">
          <div className="absolute -left-8 top-12 z-10 hidden w-44 rounded-2xl border border-[#2D5016]/15 bg-[#F5F3ED]/95 p-4 shadow-[0_18px_50px_rgba(45,80,22,.14)] md:block"><div className="mb-4 flex items-center justify-between"><span className="font-mono text-[.58rem] uppercase tracking-[.14em] text-[#697466]">Signal / 01</span><span className="size-2 rounded-full bg-[#B85C4D]" /></div><p className="font-display text-lg leading-tight text-[#2D5016]">Notice earlier. Act calmer.</p></div>
          <div className="relative aspect-[.88] overflow-hidden rounded-[2rem] rounded-tr-[7rem] border border-[#2D5016]/15 bg-[#2D5016] shadow-[0_24px_80px_rgba(45,80,22,.18)]"><img src={heroImagePath} alt={heroAlt} className="size-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#17290f]/65 via-transparent to-transparent" /><div className="absolute bottom-0 left-0 right-0 flex items-end justify-between p-6 text-[#F5F3ED] md:p-8"><div><p className="font-mono text-[.6rem] uppercase tracking-[.18em] text-[#D9DDCB]">A field photo is a beginning</p><p className="mt-2 font-display text-2xl">Not a final answer.</p></div><Camera size={26} strokeWidth={1.4} /></div></div>
          <div className="absolute -bottom-8 -right-4 grid size-28 place-items-center rounded-full bg-[#B85C4D] text-center text-[#F5F3ED] shadow-[0_12px_30px_rgba(184,92,77,.25)] md:-right-8"><div><Leaf className="mx-auto mb-1" size={21} /><span className="font-mono text-[.55rem] font-medium uppercase tracking-[.12em]">Check<br />what changed</span></div></div>
        </div>
      </div>
      <div className="pointer-events-none absolute -bottom-28 -left-28 size-80 rounded-full border border-[#2D5016]/10" /><div className="pointer-events-none absolute -bottom-16 -left-16 size-56 rounded-full border border-[#2D5016]/10" />
    </section>
    <section className="border-b border-[#2D5016]/10 bg-[#2D5016] text-[#F5F3ED]"><div className="container grid gap-8 py-8 md:grid-cols-[1fr_auto_1fr] md:items-center"><div><p className="font-mono text-[.62rem] uppercase tracking-[.18em] text-[#C6D3B8]">The field insight</p><p className="mt-2 font-display text-2xl">A better next question.</p></div><div className="hidden h-12 w-px bg-[#F5F3ED]/20 md:block" /><p className="max-w-md text-sm leading-relaxed text-[#D9DDCB]">When a leaf changes, the first decision is rarely “what treatment do I use?” It is “what should I check next?”</p></div></section>
    <section className="container py-20 md:py-28"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">Start with the signal</p><h2 className="display-lg mt-5 max-w-md text-[#2D5016]">Small symptoms are worth a second look.</h2><p className="mt-6 max-w-sm text-[#66705E]">Use the scanner for a transparent demo screen, then use the library and early warning stages to make sense of what you see.</p><Link to="/early-warning" className="mt-8 inline-flex items-center gap-2 font-mono text-xs font-medium uppercase tracking-[.15em] text-[#B85C4D]">Explore early warning <ArrowUpRight size={15} /></Link></div><div className="grid gap-3 md:grid-cols-2">{symptomSigns.slice(0,4).map((item,index)=><Link to={item.link} key={item.title} className="card-lift group rounded-2xl border border-[#2D5016]/10 bg-[#FCFBF7] p-6"><div className="mb-12 flex items-start justify-between"><span className="font-mono text-xs text-[#B85C4D]">0{index+1}</span><ArrowUpRight size={17} className="text-[#A6AEA1] transition-transform group-hover:-translate-y-1 group-hover:translate-x-1" /></div><h3 className="font-display text-2xl text-[#2D5016]">{item.title}</h3><p className="mt-3 text-sm leading-relaxed text-[#66705E]">{item.suspicious}</p><p className="mt-5 border-t border-[#2D5016]/10 pt-4 font-mono text-[.62rem] uppercase tracking-[.13em] text-[#8A9286]">Next: {item.action}</p></Link>)}</div></div></section>
    <section className="bg-[#E9E7DE] py-20 md:py-28"><div className="container"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="eyebrow">One calm workflow</p><h2 className="display-lg mt-5 max-w-xl text-[#2D5016]">From first look to next action.</h2></div><p className="max-w-xs text-sm leading-relaxed text-[#66705E]">The product is intentionally clear about what is available today and what belongs in future model work.</p></div><div className="mt-12 grid gap-3 md:grid-cols-4">{coreFeatures.map((feature)=><Link key={feature.number} to={feature.number === "01" ? "/scanner" : feature.number === "02" ? "/library" : feature.number === "03" ? "/early-warning" : "/field-monitor"} className="card-lift group rounded-2xl bg-[#F5F3ED] p-6"><div className="flex items-center justify-between"><span className="font-mono text-xs text-[#B85C4D]">{feature.number}</span><ChevronRight size={16} className="text-[#A6AEA1] transition-transform group-hover:translate-x-1" /></div><div className="mt-16"><h3 className="font-display text-2xl text-[#2D5016]">{feature.title}</h3><p className="mt-3 text-sm leading-relaxed text-[#66705E]">{feature.text}</p></div></Link>)}</div></div></section>
    <section className="container py-20"><div className="grid gap-10 rounded-[2rem] bg-[#B85C4D] p-8 text-[#F5F3ED] md:grid-cols-[1fr_auto] md:items-center md:p-12"><div><p className="font-mono text-[.63rem] uppercase tracking-[.18em] text-[#F2D4CC]">Ready when you are</p><h2 className="mt-4 max-w-xl font-display text-4xl leading-tight md:text-5xl">A screening flow that tells you where its limits are.</h2></div><Link to="/scanner" className="button-secondary w-fit border-[#F5F3ED]/40 px-6 py-4 text-[#F5F3ED] hover:bg-[#F5F3ED] hover:text-[#B85C4D]">Try demo scanner <ArrowUpRight size={16} /></Link></div></section>
  </div>;
}
